{
  "openapi": "3.0.0",
  "info": {
    "title": "Test API",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
  "paths": {
    "/users/{userId}": {
      "parameters": [
        {
          "schema": {
            "type": "integer"
          },
          "name": "userId",
          "in": "path",
          "required": true,
          "description": "Id of an existing user."
        }
      ],
      "get": {
        "summary": "Get User Info by User ID",
        "tags": [],
        "responses": {
          "200": {
            "description": "User Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "Get User Alice Smith": {
                    "value": {
                      "id": 142,
                      "firstName": "Alice",
                      "lastName": "Smith",
                      "email": "alice.smith@gmail.com",
                      "dateOfBirth": "1997-10-31",
                      "emailVerified": true,
                      "signUpDate": "2019-08-24"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User Not Found"
          }
        },
        "operationId": "get-users-userId",
        "description": "Retrieve the information of the user with the matching user ID."
      },
      "patch": {
        "summary": "Update User Information",
        "operationId": "patch-users-userId",
        "responses": {
          "200": {
            "description": "User Updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "Updated User Rebecca Baker": {
                    "value": {
                      "id": 13,
                      "firstName": "Rebecca",
                      "lastName": "Baker",
                      "email": "rebecca@gmail.com",
                      "dateOfBirth": "1985-10-02",
                      "emailVerified": false,
                      "createDate": "2019-08-24"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User Not Found"
          },
          "409": {
            "description": "Email Already Taken"
          }
        },
        "description": "Update the infromation of an existing user.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string",
                    "description": "If a new email is given, the user's email verified property will be set to false."
                  },
                  "dateOfBirth": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "Update First Name": {
                  "value": {
                    "firstName": "Rebecca"
                  }
                },
                "Update Email": {
                  "value": {
                    "email": "rebecca@gmail.com"
                  }
                },
                "Update Last Name & Date of Birth": {
                  "value": {
                    "lastName": "Baker",
                    "dateOfBirth": "1985-10-02"
                  }
                }
              }
            }
          },
          "description": "Patch user properties to update."
        }
      }
    },
    "/user": {
      "post": {
        "summary": "Create New User",
        "operationId": "post-user",
        "responses": {
          "200": {
            "description": "User Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "New User Bob Fellow": {
                    "value": {
                      "id": 12,
                      "firstName": "Bob",
                      "lastName": "Fellow",
                      "email": "bob.fellow@gmail.com",
                      "dateOfBirth": "1996-08-24",
                      "emailVerified": false,
                      "createDate": "2020-11-18"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Missing Required Information"
          },
          "409": {
            "description": "Email Already Taken"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "dateOfBirth": {
                    "type": "string",
                    "format": "date"
                  }
                },
                "required": [
                  "firstName",
                  "lastName",
                  "email",
                  "dateOfBirth"
                ]
              },
              "examples": {
                "Create User Bob Fellow": {
                  "value": {
                    "firstName": "Bob",
                    "lastName": "Fellow",
                    "email": "bob.fellow@gmail.com",
                    "dateOfBirth": "1996-08-24"
                  }
                }
              }
            }
          },
          "description": "Post the necessary fields for the API to create a new user."
        },
        "description": "Create a new user."
      }
    },
    "/Territories": {
      "get": {
        "summary": "List of PLD territories.",
        "tags": [],
        "responses": {},
        "operationId": "get-Territories"
      },
      "post": {
        "summary": "Create new PLD territory.",
        "tags": [],
        "responses": {},
        "operationId": "post-Territories"
      },
      "delete": {
        "summary": "Delete existing PLD territory.",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "operationId": "delete-Territories",
        "description": ""
      },
      "put": {
        "summary": "Update existing PLD territory.",
        "tags": [],
        "responses": {},
        "operationId": "put-Territories"
      }
    },
    "/DSL": {
      "get": {
        "summary": "List available DataSet Layers.",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "properties": {
                    "$schema": {
                      "type": "string",
                      "minLength": 1
                    },
                    "$id": {
                      "type": "string",
                      "minLength": 1
                    },
                    "type": {
                      "type": "string",
                      "minLength": 1
                    },
                    "title": {
                      "type": "string",
                      "minLength": 1
                    },
                    "description": {
                      "type": "string",
                      "minLength": 1
                    },
                    "default": {
                      "type": "object"
                    },
                    "examples": {
                      "type": "array",
                      "uniqueItems": true,
                      "minItems": 1,
                      "items": {
                        "type": "object",
                        "properties": {
                          "array": {
                            "type": "array",
                            "items": {
                              "type": "object"
                            }
                          },
                          "boolean": {
                            "type": "boolean"
                          },
                          "color": {
                            "type": "string",
                            "minLength": 1
                          },
                          "null": {},
                          "number": {
                            "type": "number"
                          },
                          "object": {
                            "type": "object",
                            "properties": {
                              "a": {
                                "type": "string",
                                "minLength": 1
                              },
                              "c": {
                                "type": "string",
                                "minLength": 1
                              }
                            },
                            "required": [
                              "a",
                              "c"
                            ]
                          },
                          "string": {
                            "type": "string",
                            "minLength": 1
                          }
                        },
                        "required": [
                          "boolean",
                          "color",
                          "number",
                          "string"
                        ]
                      }
                    },
                    "required": {
                      "type": "array",
                      "items": {
                        "type": "object"
                      }
                    },
                    "properties": {
                      "type": "object",
                      "required": [
                        "array",
                        "boolean",
                        "color",
                        "null",
                        "number",
                        "object",
                        "string"
                      ],
                      "properties": {
                        "array": {
                          "type": "object",
                          "required": [
                            "$id",
                            "type",
                            "title",
                            "description",
                            "default",
                            "examples",
                            "additionalItems",
                            "items"
                          ],
                          "properties": {
                            "$id": {
                              "type": "string",
                              "minLength": 1
                            },
                            "type": {
                              "type": "string",
                              "minLength": 1
                            },
                            "title": {
                              "type": "string",
                              "minLength": 1
                            },
                            "description": {
                              "type": "string",
                              "minLength": 1
                            },
                            "default": {
                              "type": "array",
                              "items": {
                                "type": "object"
                              }
                            },
                            "examples": {
                              "type": "array",
                              "items": {
                                "type": "object",
                                "properties": {
                                  "0": {
                                    "type": "array",
                                    "uniqueItems": true,
                                    "items": {
                                      "type": "object"
                                    }
                                  }
                                }
                              }
                            },
                            "additionalItems": {
                              "type": "boolean"
                            },
                            "items": {
                              "type": "object",
                              "required": [
                                "$id",
                                "anyOf"
                              ],
                              "properties": {
                                "$id": {
                                  "type": "string",
                                  "minLength": 1
                                },
                                "anyOf": {
                                  "type": "array",
                                  "uniqueItems": true,
                                  "minItems": 1,
                                  "items": {
                                    "type": "object",
                                    "properties": {
                                      "$id": {
                                        "type": "string",
                                        "minLength": 1
                                      },
                                      "type": {
                                        "type": "string",
                                        "minLength": 1
                                      },
                                      "title": {
                                        "type": "string",
                                        "minLength": 1
                                      },
                                      "description": {
                                        "type": "string",
                                        "minLength": 1
                                      },
                                      "default": {
                                        "type": "number"
                                      },
                                      "examples": {
                                        "type": "array",
                                        "items": {
                                          "type": "object"
                                        }
                                      }
                                    },
                                    "required": [
                                      "$id",
                                      "type",
                                      "title",
                                      "description",
                                      "default"
                                    ]
                                  }
                                }
                              }
                            }
                          }
                        },
                        "boolean": {
                          "type": "object",
                          "required": [
                            "$id",
                            "type",
                            "title",
                            "description",
                            "default",
                            "examples"
                          ],
                          "properties": {
                            "$id": {
                              "type": "string",
                              "minLength": 1
                            },
                            "type": {
                              "type": "string",
                              "minLength": 1
                            },
                            "title": {
                              "type": "string",
                              "minLength": 1
                            },
                            "description": {
                              "type": "string",
                              "minLength": 1
                            },
                            "default": {
                              "type": "boolean"
                            },
                            "examples": {
                              "type": "array",
                              "items": {
                                "type": "object"
                              }
                            }
                          }
                        },
                        "color": {
                          "type": "object",
                          "required": [
                            "$id",
                            "type",
                            "title",
                            "description",
                            "default",
                            "examples"
                          ],
                          "properties": {
                            "$id": {
                              "type": "string",
                              "minLength": 1
                            },
                            "type": {
                              "type": "string",
                              "minLength": 1
                            },
                            "title": {
                              "type": "string",
                              "minLength": 1
                            },
                            "description": {
                              "type": "string",
                              "minLength": 1
                            },
                            "default": {
                              "type": "string"
                            },
                            "examples": {
                              "type": "array",
                              "items": {
                                "type": "object"
                              }
                            }
                          }
                        },
                        "null": {
                          "type": "object",
                          "required": [
                            "$id",
                            "type",
                            "title",
                            "description",
                            "examples"
                          ],
                          "properties": {
                            "$id": {
                              "type": "string",
                              "minLength": 1
                            },
                            "type": {
                              "type": "string",
                              "minLength": 1
                            },
                            "title": {
                              "type": "string",
                              "minLength": 1
                            },
                            "description": {
                              "type": "string",
                              "minLength": 1
                            },
                            "default": {},
                            "examples": {
                              "type": "array",
                              "items": {
                                "type": "object"
                              }
                            }
                          }
                        },
                        "number": {
                          "type": "object",
                          "required": [
                            "$id",
                            "type",
                            "title",
                            "description",
                            "default",
                            "examples"
                          ],
                          "properties": {
                            "$id": {
                              "type": "string",
                              "minLength": 1
                            },
                            "type": {
                              "type": "string",
                              "minLength": 1
                            },
                            "title": {
                              "type": "string",
                              "minLength": 1
                            },
                            "description": {
                              "type": "string",
                              "minLength": 1
                            },
                            "default": {
                              "type": "number"
                            },
                            "examples": {
                              "type": "array",
                              "items": {
                                "type": "object"
                              }
                            }
                          }
                        },
                        "object": {
                          "type": "object",
                          "required": [
                            "$id",
                            "type",
                            "title",
                            "description",
                            "default",
                            "examples",
                            "required",
                            "properties",
                            "additionalProperties"
                          ],
                          "properties": {
                            "$id": {
                              "type": "string",
                              "minLength": 1
                            },
                            "type": {
                              "type": "string",
                              "minLength": 1
                            },
                            "title": {
                              "type": "string",
                              "minLength": 1
                            },
                            "description": {
                              "type": "string",
                              "minLength": 1
                            },
                            "default": {
                              "type": "object"
                            },
                            "examples": {
                              "type": "array",
                              "uniqueItems": true,
                              "minItems": 1,
                              "items": {
                                "type": "object",
                                "properties": {
                                  "a": {
                                    "type": "string",
                                    "minLength": 1
                                  },
                                  "c": {
                                    "type": "string",
                                    "minLength": 1
                                  }
                                },
                                "required": [
                                  "a",
                                  "c"
                                ]
                              }
                            },
                            "required": {
                              "type": "array",
                              "items": {
                                "type": "object"
                              }
                            },
                            "properties": {
                              "type": "object",
                              "required": [
                                "a",
                                "c"
                              ],
                              "properties": {
                                "a": {
                                  "type": "object",
                                  "required": [
                                    "$id",
                                    "type",
                                    "title",
                                    "description",
                                    "default",
                                    "examples"
                                  ],
                                  "properties": {
                                    "$id": {
                                      "type": "string",
                                      "minLength": 1
                                    },
                                    "type": {
                                      "type": "string",
                                      "minLength": 1
                                    },
                                    "title": {
                                      "type": "string",
                                      "minLength": 1
                                    },
                                    "description": {
                                      "type": "string",
                                      "minLength": 1
                                    },
                                    "default": {
                                      "type": "string"
                                    },
                                    "examples": {
                                      "type": "array",
                                      "items": {
                                        "type": "object"
                                      }
                                    }
                                  }
                                },
                                "c": {
                                  "type": "object",
                                  "required": [
                                    "$id",
                                    "type",
                                    "title",
                                    "description",
                                    "default",
                                    "examples"
                                  ],
                                  "properties": {
                                    "$id": {
                                      "type": "string",
                                      "minLength": 1
                                    },
                                    "type": {
                                      "type": "string",
                                      "minLength": 1
                                    },
                                    "title": {
                                      "type": "string",
                                      "minLength": 1
                                    },
                                    "description": {
                                      "type": "string",
                                      "minLength": 1
                                    },
                                    "default": {
                                      "type": "string"
                                    },
                                    "examples": {
                                      "type": "array",
                                      "items": {
                                        "type": "object"
                                      }
                                    }
                                  }
                                }
                              }
                            },
                            "additionalProperties": {
                              "type": "boolean"
                            }
                          }
                        },
                        "string": {
                          "type": "object",
                          "required": [
                            "$id",
                            "type",
                            "title",
                            "description",
                            "default",
                            "examples"
                          ],
                          "properties": {
                            "$id": {
                              "type": "string",
                              "minLength": 1
                            },
                            "type": {
                              "type": "string",
                              "minLength": 1
                            },
                            "title": {
                              "type": "string",
                              "minLength": 1
                            },
                            "description": {
                              "type": "string",
                              "minLength": 1
                            },
                            "default": {
                              "type": "string"
                            },
                            "examples": {
                              "type": "array",
                              "items": {
                                "type": "object"
                              }
                            }
                          }
                        }
                      }
                    },
                    "additionalProperties": {
                      "type": "boolean"
                    }
                  },
                  "required": [
                    "$schema",
                    "$id",
                    "type",
                    "title",
                    "description",
                    "default",
                    "examples",
                    "required",
                    "properties",
                    "additionalProperties"
                  ]
                },
                "examples": {}
              }
            }
          }
        },
        "operationId": "get-DSL",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "query"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "": {
                    "anyOf": [
                      {
                        "properties": {
                          "": {
                            "type": [
                              "string",
                              "number",
                              "integer"
                            ]
                          }
                        }
                      },
                      {}
                    ],
                    "type": "object"
                  }
                }
              },
              "examples": {}
            }
          },
          "description": ""
        }
      },
      "put": {
        "summary": "Update an existing DataSet Layer.",
        "tags": [],
        "responses": {},
        "operationId": "put-DSL"
      },
      "delete": {
        "summary": "Delete an existing DataSet Layer.",
        "tags": [],
        "responses": {},
        "operationId": "delete-DSL"
      },
      "post": {
        "summary": "Create a new DataSet Layer.",
        "tags": [],
        "responses": {},
        "operationId": "post-DSL",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "title": "User",
        "type": "object",
        "description": "",
        "x-examples": {
          "Alice Smith": {
            "id": 142,
            "firstName": "Alice",
            "lastName": "Smith",
            "email": "alice.smith@gmail.com",
            "dateOfBirth": "1997-10-31",
            "emailVerified": true,
            "signUpDate": "2019-08-24"
          }
        },
        "properties": {
          "id": {
            "type": "integer",
            "description": "Unique identifier for the given user."
          },
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "dateOfBirth": {
            "type": "string",
            "format": "date",
            "example": "1997-10-31"
          },
          "emailVerified": {
            "type": "boolean",
            "description": "Set to true if the user's email has been verified."
          },
          "createDate": {
            "type": "string",
            "format": "date",
            "description": "The date that the user was created."
          }
        },
        "required": [
          "id",
          "firstName",
          "lastName",
          "email",
          "emailVerified"
        ]
      }
    },
    "securitySchemes": {},
    "responses": {
      "200": {
        "description": "Example response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "": {
                  "type": "string"
                }
              }
            },
            "examples": {
              "example-1": {
                "value": {
                  "id": "string",
                  "": "string"
                }
              }
            }
          },
          "application/xml": {
            "schema": {
              "type": "object",
              "properties": {}
            }
          },
          "multipart/form-data": {
            "schema": {
              "type": "object",
              "properties": {}
            }
          }
        }
      }
    }
  }
}